services:
  mc-agent:
    build: .
    env_file:
      - ./.env
    environment:
      DETECT_MODE: "query"
      MC_HOST: "minecraft"     # container_name of MC
      MC_QUERY_PORT: "25565"
    networks:
      - mc-network
    restart: unless-stopped

networks:
  mc-network:
    external: true












