mc-agent:
    build: .
    depends_on: [mc]
    env_file:
      - ./.env
    environment:
      DETECT_MODE: "query"
      MC_HOST: "mc"              # service name on the compose network
      MC_QUERY_PORT: "25565"
      # SERVER_ID/AGENT_KEY/INGEST_URL/DRY_RUN pulled from .env
    # host metrics (optional); remove if you want container metrics instead
    pid: host
    restart: unless-stopped
